### ISSUE TITLE
2. simple math, 2/32 issue [solved]

### ISSUE THREAD

**Issue by MeadowValley** [clojurecademy/4Clojure#11]
Hey,
the instructions are clear:
> 1. Enter only enough to fill in the blank (in this case, a single number) - do not retype the whole problem.
> (= (- 10 (* 2 3)) #_blank)

I entered 
```
(ns simple-math)
;;Write your code under this comment, it will fill the blank.
(= (- 10 (* 2 3)) 4)
```

but the console keeps saying:
```
1. instruction failed.
(= (- 10 (* 2 3)) (= (- 10 (* 2 3)) 4)) -> This form does not return true!
```
I don't see how (= 4 true), what the error message says, can ever be true.
If I enter (+ 4 0) as solution, it accepts it.

If I enter something like
`(= 1 1)`
it keeps saying:
```
1. instruction failed.
(= (- 10 (* 2 3)) (= 1 1)) -> This form does not return true!
```

I tried reloading the site, moving forward/backward in course, but that didn't fix the problem.
I'm using Firefox 57.

![c7b0d59c-3a0a-4a76-9ee6-9462261afefd](https://user-images.githubusercontent.com/10567075/31513197-d2bd716e-af8d-11e7-88a6-d538e82092fd.png)

edit: I have the same problem with all of the following slides...
edit2: I guess I got the instructions wrong. Maybe it would be better to give an example how to understand the instructions, so this doesn't happen to other people. -> SOLVED

**Comment by ertugrulcetin** [comment]
Hey @DerKnecht thanks for reaching out! Basically you need to provide code that fills the blank so you should not type the whole problem. In this case you need to provide **4** as an answer. Also you are right providing example would be really helpful I've seen couple of users had the same problem.
