### ISSUE TITLE
3. Intro to Strings

### ISSUE THREAD

**Issue by wviana** [clojurecademy/4Clojure#14]
I've entered the code 

```
(ns intro-to-strings)

;;Write your code under this comment, it will fill the blank.
(= "HELLO WORLD" (.toUpperCase "hello world"))
```

When I do run using REPL I get a true response.
When a I Click RUN I get a 

> 1. instruction failed.
> 
> (= (= "HELLO WORLD" (.toUpperCase "hello world")) (.toUpperCase "hello world")) -> This form does not return true!

**Comment by ertugrulcetin** [comment]
@wviana basically you just need to type just `"HELLO WORLD"` NOT the whole question `(= "HELLO WORLD" (.toUpperCase "hello world")`, your answer will be filled in the blank

**Comment by wviana** [comment]
@ertugrulcetin Thank you very much.

I think it could be better explained in the first lessons of this type.

**Comment by ertugrulcetin** [comment]
@wviana yeah you are right! There were people who had same problem as well. I'll fix this, thank you so much for reaching out!
