### ISSUE TITLE
Repl not working

### ISSUE THREAD

**Issue by JimLynchCodes** [clojurecademy/4Clojure#15]
I'm doing code katas fizzbuzz problem, and I cannot run anything from the repl. It displays this:

`_=> #'sandbox-ns-jimtheman/fizzbuzz_`

but I cannot type anything.

**Comment by ertugrulcetin** [comment]
@JimTheMan thanks for reaching out! **REPL** is for getting fast feedbacks it does not make you pass problems you need to use **Run** button for that. This result(`#'sandbox-ns-jimtheman/fizzbuzz_`) means you have written a function and you are getting **var** of it if you want to see the result of this function on REPL then you need to call `fizzbuzz`. Like I said REPL is for experimenting your code and providing fast iterations.

**Comment by JimLynchCodes** [comment]
@ertugrulcetin right, but how do I run fizzbuzz from the repl? I cannot type anything in the repl. That is why I am opening issue for a bug.

**Comment by ertugrulcetin** [comment]
@JimTheMan Hmm interesting, which OS and Browser are you running? You can't type anything in the editor right? Or after clicking REPL, you are trying to type some code in the console(where the results are)? If that's the case, you can not type anything in console, it's just for displaying results. You can use **REPL** for **fizzbuzz** like that: 

```
(defn fizzbuzz [x]
 (let [v [(= (mod x 3) 0) (= (mod x 5) 0)]]
  ({[true false]  "fizz"
    [false true]  "buzz"
    [true true]   "fizzbuzz"
    [false false] (str x)} v)))

(fizzbuzz 10)

=> #'sandbox-ns-ertu/fizzbuzz

=> buzz
```

**Comment by JimLynchCodes** [comment]
ah ok. I didn't realize you were not supposed to be able to type into the command prompt.

It would be cool if you could type `(fizzbuzz 3)` right into the console.
