### ISSUE TITLE
Slide 10 - Control Structures, what do I not understand?

### ISSUE THREAD

**Issue by abankspdx** [clojurecademy/4Clojure#16]
So I got a little cheeky and I combined a previous concept (let) to my code for an example function, and I get error: `Apparently you did not use if function properly.`

My code:

```
(ns control-structures)
(let [a "blue"]
  (if (== 0 (compare a "red")) (println "red") (println "blue")))
```

It prints correctly based on the output of the `if`, but the REPL is still telling me I did not use an `if` correctly.

**Comment by ertugrulcetin** [comment]
@alexanderbanks Thank you for reaching out! It expects at top level which is wrong at the moment, I will fix this. This code is working: 

```
(def a "blue")

(if (== 0 (compare a "red")) (println "red") (println "blue"))
```

**Comment by abankspdx** [comment]
Oh I understand. I didn't realize the `if` had to be the at the top level. Thanks!

**Comment by ertugrulcetin** [comment]
@alexanderbanks it's fixed now!
