### ISSUE TITLE
3. Let's do some math

### ISSUE THREAD

**Issue by mladencikara** [clojurecademy/4Clojure#17]
I have put:
(ns math-operations)

(+ 1 2 3)

(println (+ 1 2 3))
(+ 5 (* 5 (- 7 2 1)))

In console and when I run it returns:
3. instruction failed.

Apparently you did not copy and paste properly.Please check copy paste order.

6

**Comment by ertugrulcetin** [comment]
@mladencikara thanks for reaching out! you need to print this expression: `(+ 5 (* 5 (- 7 2 1)))` so code will end up like this:

```
(ns math-operations)

(+ 1 2 3)

(println (+ 1 2 3))

(println (+ 5 (* 5 (- 7 2 1))))
```

**Comment by mladencikara** [comment]
Thanks.
