### ISSUE TITLE
Rearranging Code: ->>

### ISSUE THREAD

**Issue by TamaraBucic** [clojurecademy/4Clojure#2]
I think here is a bug

(= (#_blank + (map inc (take 3 (drop 2 [2 5 4 1 3 6]))))
   (->> [2 5 4 1 3 6] (drop 2) (take 3) (map inc) (#_blank))
   11)

first blank requires just reduce, the other one reduce +

**Comment by ertugrulcetin** [comment]
@TamaraMystic You are right! Fixed, thank you
