### ISSUE TITLE
Exercism.io #10, Test 4 has two tests expecting wrong value

### ISSUE THREAD

**Issue by KingCode** [clojurecademy/4Clojure#20]
"For a shape to be a triangle at all, all sides have to be of length > 0, and the sum of the lengths of any two sides must be greater than or equal to the length of the third side."

Then the two following tests have the wrong expected value, which should be :isosceles instead
(= :illogical (triangle-type 1 2 1)) ;; 1 + 1 >= 2, 2 + 1 >= 1 therefore a valid triangle
(= :illogical (triangle-type 2 4 2));; idem

**Comment by ertugrulcetin** [comment]
@KingCode hi there! I'll check that, also could you move it to https://github.com/clojurecademy/exercism.io/issues, it's not 4Clojure's problem

**Comment by KingCode** [comment]
OK...done! The link I clicked from the exercism.io page sent me here - maybe it needs to be fixed? 
Thanks.

**Comment by ertugrulcetin** [comment]
Yeah I will also fix that too
