### ISSUE TITLE
12/46 get capitals

### ISSUE THREAD

**Issue by AlexanderChenNL** [clojurecademy/4Clojure#26]
Just wondering was this really what you where looking for? it seems like there should have been an easier way

`(def uppercase_list
  #{\A \B \C \D \E \F \G \H \I \J \K \L \M \N \P \Q \R \S \T \U \O \V \W \X \Y \Z})

(defn get-the-caps [value]
  (loop [times  0
         result_str ""]
    (if (<= times (dec (count value)))
      (do   (if (uppercase_list (nth value times)) 
            (recur (inc times) (str (nth value times) result_str))
            (recur (inc times) result_str)))
      (apply str (reverse result_str)))))`

**Comment by AlexanderChenNL** [comment]
Could you otherwise give me your solution, then I can compare.

**Comment by ertugrulcetin** [comment]
Hi @AlexanderChenNL thanks for reaching out! Sorry I forgot to reply to this issue.
Here is the solution:

```
(defn only-capitals 
  [s] 
  (apply str (filter #(Character/isUpperCase %1) (seq s))))
```
