### ISSUE TITLE
Clojure Basics: 11/11 Functions Instructions Not Clear

### ISSUE THREAD

**Issue by suguleasa** [clojurecademy/4Clojure#28]
Under the Clojure Basics 11/11 Functions chapter, there is a section titled "Before you start".
The following is not clear and should be rephrased:

"Run previous instructions functionality is ON.
(e.g. before executing 3. instruction 1. and 2. instructions going to be executed to check that they pass or not)"

**Comment by ertugrulcetin** [comment]
Which means if you are on third instructions your code will be checked for first and second one then it's going to be checked for third one. Is it clear now?
