### ISSUE TITLE
Fizzbuzz Test For Divisible by 15 is Incorrect

### ISSUE THREAD

**Issue by jesskrich** [clojurecademy/4Clojure#29]
This is a correct function:

`(defn fizzbuzz
  [n]
  (if (> n 0)
    	(cond 
      		(= (mod n 15) 0) "fizzbuzz"
      		(= (mod n 3) 0) "fizz"
      		(= (mod n 5) 0) "buzz"
	         :else (str n))))
    `

And the test for "Return “fizzbuzz” if given number dividable by 15" throw this error:

`3. instruction failed.

(= (fizzbuzz 0) "fizzbuzz") => (= nil "fizzbuzz") -> This assertion does not return true!
`

**Comment by ertugrulcetin** [comment]
@jesskrich thanks for reaching out, actually it's correct your function should return "fizzbuzz" when  n is `0`.

**Comment by jesskrich** [comment]
Then the instructions are incorrect because it says:

`For a given natural number greater than zero return:

“fizz” if the number is dividable by 3
“buzz” if the number is dividable by 5
“fizzbuzz” if the number is dividable by 15`

**Comment by ertugrulcetin** [comment]
you are right I need to update the problem
