### ISSUE TITLE
4 not accepted as answer in 4Clojure 2/32

### ISSUE THREAD

**Issue by tosh** [clojurecademy/4Clojure#3]
<img width="1082" alt="screenshot 2017-10-03 20 19 06" src="https://user-images.githubusercontent.com/14825/31141639-3e6b2ab8-a878-11e7-81cc-7d58524d8219.png">

**Comment by ertugrulcetin** [comment]
@tosh basically you need to type just **4** _NOT_ the whole question( (= (- 10 (* 2 3)) 4) ), your answer will be filled in the blank

**Comment by tosh** [comment]
Ah, got it, thanks
