### ISSUE TITLE
16. Hello World

### ISSUE THREAD

**Issue by knowingpark** [clojurecademy/4Clojure#35]
Question 16 is not accepting 

(fn [n] (str "Hello, "  n))

when the repl says this is true:
(= ((fn [n] (str "Hello, "  n))  "Dave!")  "Hello, Dave!")

Is it me ?

**Comment by ertugrulcetin** [comment]
hi @knowingpark thanks for reaching out!

Here is the working solution:
`(fn [n] (str "Hello, " n "!"))`

It seems like you forgot exclamation point :)

**Comment by knowingpark** [comment]
Oops. Thanks!
