### ISSUE TITLE
Answer 3 not accepted in subjects/17592186045446

### ISSUE THREAD

**Issue by jinwood** [clojurecademy/4Clojure#4]
On page https://github.com/clojurecademy/4Clojure/issues/new trying to submit answer 3.

First I free typed the example and the submission failed, then I overwrote my code with the provided solution and the code still failed. My editor window currently looks like this:

```
(ns math-operations)
(+ 1 2 3)
(println (+ 1 2 3))
(+ 5 (* 5 (- 7 2 1)))
```

And my free types window looked like this:
(ns math-operations)
```
(+ 1 2 3)
(println (+ 1 2 3))
(+ 5(* 5 (- 7 2 1)))
```

**Comment by ertugrulcetin** [comment]
@jinwood Instruction says: "_Please_ **print** _this code under the previous code that prints: (+ 1 2 3)_"

Basically you need to write like this:
```
(ns math-operations)

(+ 1 2 3)

(println (+ 1 2 3))

(println (+ 5 (* 5 (- 7 2 1))))
```
