### ISSUE TITLE
2. Simple Math

### ISSUE THREAD

**Issue by FachriHammadFP** [clojurecademy/4Clojure#43]
Hello Writer 4Clojure, thanks for Clojure course. 
I'm a junior/noob about clojure and i try to answer Simple Math Section. 
I think i was wrong for answer (= (- 10 (* 2 3)) 4) 

![Screenshot (80)](https://user-images.githubusercontent.com/31992756/77224248-53000c80-6b96-11ea-8a8e-bf856bfc9401.png)
In picture above i was wrong for answer in RUN

![Screenshot (81)](https://user-images.githubusercontent.com/31992756/77224266-80e55100-6b96-11ea-978e-5212ac1a7429.png)
But in picture above in REPL is true. 

Can you help me for solution. 
Thanks Before

**Comment by ertugrulcetin** [comment]
Hi @FachriHammadFP thanks for reaching out! You are going to replace #_blank with the result.
Like you are not going to type all form, just write number `4` under the comment.

```clojure
;;Write your code under this comment....
4
```

**Comment by FachriHammadFP** [comment]
Thanks Mr, its very cool course. Thanks
