### ISSUE TITLE
Palindrome detector exercise can be cheated

### ISSUE THREAD

**Issue by Thau** [clojurecademy/4Clojure#5]
There are no tests that start and end with the same element, but are not a palindrome, so the exercise can be cheated using

```clojure
(defn palindrome
  [s]
  (= (first s) (last s)))
```

**Comment by ertugrulcetin** [comment]
@Thau You are right! Thank you for letting me now, I'll fix this

**Comment by ertugrulcetin** [comment]
@Thau it's fixed now!
