### ISSUE TITLE
my-multi function issue

### ISSUE THREAD

**Issue by Erynvorn** [clojurecademy/4Clojure#6]
There is  not enough indications how to manage a function with more than 2 parameters to solve the last exercise to create my-multi function. Again, you need to know LISP to learn CLOJURE, which is quite frustrating for a newbie.

**Comment by ertugrulcetin** [comment]
@Erynvorn you are right course needs to be more clear about that, I will add needed information to the course. Thank you for letting me know!

**Comment by ertugrulcetin** [comment]
@Erynvorn fixed it!

**Comment by Erynvorn** [comment]
Hi, thanks for the upgrade. I see you provided the full solution. 

I don’t mind coding a recurrence, my issue was the unknown input form. hinting with [ a & the-rest] would have been sufficient.  
Or adding an intermediate exercise with a similar input but no recurrence. 
I never seen the concept of a & % the-rest before. This was the new item. 

I really appreciate your efforts and I apologize if my comments was too strong. I get frustrated at time and I shouldn’t react. 

Your contribution is great and very much appreciated. 

Best regards,

Daniel

**Comment by ertugrulcetin** [comment]
Thank you so much for your feedback. You are totally right, I should have added that % information before asking it so I'm gonna add more information about Clojure Basics.
