### ISSUE TITLE
str/join (slide 8) shows "Instruction Failed", even though result prints correctly

### ISSUE THREAD

**Issue by KingCode** [clojurecademy/4Clojure#7]
![image](https://user-images.githubusercontent.com/45764/31356340-b473f6da-ad0b-11e7-9255-4c16a4c863fe.png)

**Comment by ertugrulcetin** [comment]
Hi @KingCode thanks for reaching out!,

You should write like this actually:

```
(ns string-example
  (:require [clojure.string :as str]))

(str/join ["Hello" "World"])
```

**Comment by anthonyspizza** [comment]
I came across this as well. I looked at examples for join on clojuredocs and they all used the separator. I know the separator is optional, but shouldn't they both be accepted? I almost created an issue until I saw this.

**Comment by ertugrulcetin** [comment]
@jaerme  Thank you for reaching out! Yeah they should be accepted but for this chapter it requires that form only. I think I need to change it and make sure that both approaches should be accepted.

**Comment by KingCode** [comment]
That is what I was implying when I opened the original ticket.

Thank you,
JF

**Comment by ertugrulcetin** [comment]
@KingCode I'll fix this you guys are right.

**Comment by ertugrulcetin** [comment]
@KingCode it's fixed now!
